**Numpy**

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.
In this lesson, we will cover the basics of Numpy, focusing on arrays and vectorized operations.

In [2]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

Creat arrays

In [4]:
#One dimension array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#Two dimensions array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 columns
#print(arr2)


array([[1, 2, 3, 4, 5]])

In [ ]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2.shape) # 2 row and 5 columns
print(arr2)

Array methods

Arange

É usado para criar arrays com valores igualmente espaçados, de forma semelhante à função range() do Python, mas devolvendo um array NumPy em vez de um iterador.

In [7]:
arrayPares=np.arange(0,10,2)
print(arrayPares)
print(arrayPares.reshape(5,1))

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


Ones

Sintaxe: numpy.ones(shape, dtype=float)
O método ones() é usado para criar um array preenchido apenas com o valor 1.
Por padrao utiliza float, mas pode ser definido para int utilizando dtype=int

In [15]:
#Array de ones unidirecional
print("Array 1D:")
arrayOnes=np.ones(5,dtype=int)
print(arrayOnes)

print("")

#Array de ones bidirecional
print("Array 2D:")
arrayOnes2=np.ones((5,2), dtype=int)
print(arrayOnes2)

Array 1D:
[1 1 1 1 1]

Array 2D:
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
