**Numpy**

NumPy is a fundamental library for scientific computing in Python. 
It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.
In this lesson, we will cover the basics of Numpy, focusing on arrays and vectorized operations.

In [2]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

Creat arrays

In [3]:
#One dimension array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [91]:
#Two dimensions array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 columns
#print(arr2)


array([[1, 2, 3, 4, 5]])

In [5]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2.shape) # 2 row and 5 columns
print(arr2)

(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


**Array methods**

Arange

É usado para criar arrays com valores igualmente espaçados, de forma semelhante à função range(), mas devolvendo um array NumPy em vez de um iterador.

In [6]:
arrayPares=np.arange(0,10,2)
print(arrayPares)
print(" ")
print(arrayPares.reshape(5,1))

[0 2 4 6 8]
 
[[0]
 [2]
 [4]
 [6]
 [8]]


Ones

O método ones() é usado para criar um array preenchido apenas com o valor 1.
Por padrao utiliza float, mas pode ser definido para int utilizando dtype=int
Sintaxe: numpy.ones(shape, dtype=float)

In [8]:
#Array de ones unidirecional
print("Array 1D:")
arrayOnes=np.ones(5,dtype=int)
print(arrayOnes)

print("")

#Array de ones bidirecional
print("Array 2D:")
arrayOnes2=np.ones((5,2), dtype=int)
print(arrayOnes2)

Array 1D:
[1 1 1 1 1]

Array 2D:
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


eye

O método eye() é usado para criar matrizes identidade (ou variantes delas).

np.eye() cria um array 2D onde:
Os elementos da diagonal principal são 1;
Os restantes elementos são 0.

Sintaxe: np.eye(N, M=None, k=0, dtype=float)
N: Número de linhas

M (opcional): Número de colunas
Se não for indicado, assume M = N (matriz quadrada)

k: Indica qual diagonal recebe os valores 1
k = 0 → diagonal principal
k > 0 → diagonal acima da principal
k < 0 → diagonal abaixo da principal

dtype: Tipo de dados (int, float, etc.)

In [14]:
# Identity matrix
identityMatrix=np.eye(3,dtype=int)
print(identityMatrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [24]:
# Rectangular matrix (3,5)
rectMatrix=np.eye(3,5,dtype=int)
print(rectMatrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


In [26]:
#Diagonal above the main
diagonalAbove=np.eye(3,k=1,dtype=int)
print(diagonalAbove)

print("")

#Diagonal below the main
diagonalBelow=np.eye(3,k=-1,dtype=int)
print(diagonalBelow)

[[0 1 0]
 [0 0 1]
 [0 0 0]]

[[0 0 0]
 [1 0 0]
 [0 1 0]]


Attributes of numpy array

In [ ]:
array3=np.array([[1,2,3],[4,5,6]])

print(f"Array:\n {array3}")
print("")P
print(f"Shape: {array3.shape}") #Output:(2,3)
print(f"Number of dimensions:  {array3.ndim}")
print(f"Size (number of elements): {array3.size}")
print(f"Data type: {array3.dtype}") # May vary based on SO plataform
print(f"Item size (in bytes): {array3.itemsize}")

Array:
 [[1 2 3]
 [4 5 6]]

Shape: (2, 3)
Number of dimensions:  2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


**Vectorized operation**

São operações realizadas directamente sobre arrays inteiros, sem usar ciclos for explícitos em Python.


In [ ]:
array4=np.array([1,2,3,4,5])
array5=np.array([10,20,30,40,50])

# Element wise addition
print(f"Addition: {array4+array5}")


# Element wise substraction
print(f"Substraction: {array4-array5}")


# Element wise multiplication
print(f"Multiplication: {array4*array5}")


# Element wise division
print(f"Division: {array4/array5}")

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


**Universal function**

It's a function that is applied for all arrays elements.

In [ ]:
array6=np.array([4,5,6,7,8,9])

print("Square root: ")
#Square root
squareRoot=np.sqrt(array6)
print(squareRoot)
print("")
print("Exponential:")

#Exponential
exponentialArray=np.exp(array6)
print(exponentialArray)


print("")

#Sin
print("Sin:")
sinArray=np.sin(array6)
print(sinArray)


print("")
#Natural log
print("Natural log:")
naturalLogArray= np.log(array6)
print(naturalLogArray)

Square root: 
[2.         2.23606798 2.44948974 2.64575131 2.82842712 3.        ]

Exponential:
[  54.59815003  148.4131591   403.42879349 1096.63315843 2980.95798704
 8103.08392758]

Sin:
[-0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]

Natural log:
[1.38629436 1.60943791 1.79175947 1.94591015 2.07944154 2.19722458]
[4 5 6 7 8 9]


**Array slicing and Indexing**

In [70]:
#Array indexing
array7=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(f"Array: \n{array7}\n")


# Select the element of the first row and first column
print(array7[0][0],"\n")

# Select the elements 7, 8, 11 and 12
print(array7[1:,2:],"\n")


# Select the elements 3, 4, 7 and 8
print(array7[0:2,2:],"\n")

# Select the elements 6, 7, 10 and 11
print(array7[1:,1:3],"\n")

Array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

1 

[[ 7  8]
 [11 12]] 

[[3 4]
 [7 8]] 

[[ 6  7]
 [10 11]] 



**Modify array elements**

In [ ]:
array7=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [71]:
#Modify the element of the first row and first column
array7[0,0]=100
print(array7)

print("")

#Modify all elements of the second row and all columns
array7[1:]=100
print(array7)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


**Statistical concepts**

Normalization (normalização): é um processo de pré-processamento de dados que consiste em ajustar os valores de uma variável para uma escala comum, sem alterar a relação entre eles.


In [74]:
#Normalizacao Z-score(Standardization)
data=np.array([1,2,3,4,5])

#Calculate the mean and standard deviation
mean=np.mean(data)
stdDeviation=np.std(data)

#Normalize the data
normalizedData=(data-mean)/stdDeviation
print(f"Normalized data:\n {normalizedData}")

Normalized data:
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [76]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean=np.mean(data)
print(f"Mean: {mean}")

#Median
median=np.median(data)
print(f"Median: {median}")

#Standard deviation
stdDeviation=np.std(data)
print(f"Standard deviation: {stdDeviation}")

#Variance
variance=np.var(data)
print(f"Variance: {variance}")



Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Variance: 8.25


**Logical operation**

In [ ]:
data=np.array([1,2,3,4,5,6,7,8,9,10])
#Select all elements greater than five
dataGreater5=data[data>5]
print(dataGreater5,"\n")


#Select all elements greater than five and less or equal 8
dataGreater5Less8=data[(data>5) & (data<=8)] #To select two or more condictions, we need to use parentheses () and the symbol (&) for logical and.
print(dataGreater5Less8)

print("")

#Even numbers
dataEven=data[data%2==0]
print(dataEven)

[ 6  7  8  9 10] 

[6 7 8]

[ 2  4  6  8 10]
